spring:
  datasource:
    url: jdbc:mysql://db:3306/java_training?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: training
    password: training
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

