spring:
  profiles:
    active: local
  application:
    name: user-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka/
feign:
  hystrix:
    enabled: true
server:
  port: 8082
